# Hugo variables
#
baseurl = "https://santoshchaudhary.github.io/qryptal/"
themesDir = "themes"
publishDir = "docs"
languageCode = "en-us"
title = " "
theme = "bootstrap"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
disqusShortname = "https-santoshchaudhary-github-io-qryptal"
googleAnalytics = ""

#googleAnalytics = "UA-123-45"
#disqusShortname = "XYW"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"


#[[menu.navbar]]
  #  name = "Link 1"
  #  url = "https://santoshchaudhary.github.io/qryptal/"


# Theme variables
#
[params]
  # Site author
  author = "Qryptal"
  # Description/subtitle for homepage (can be Markdown)
  description = " "

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  #   menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  #custom_navbar = true

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true
  imagedir = "img/"


[params.sidebar]
  # Optional about block for sidebar (can be Markdown)
    about = " "

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
