# Hugo variables
#
baseurl = "https://santoshchaudhary.github.io/qryptal/"
themesDir = "themes"
publishDir = "docs"
languageCode = "en-us"
title = " "
theme = "bootstrap"


paginate = 5
disqusShortname = "https-santoshchaudhary-github-io-qryptal"
googleAnalytics = ""

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

#[[menu.navbar]]
  #  name = "Link 1"
  #  url = "https://santoshchaudhary.github.io/qryptal/"

[params]
  author = "Qryptal"
  description = " "
  date_format = "Mon Jan 02, 2006"
  sidebarBehavior = 1
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "cover.jpg"

  imageGallery = true


[params.sidebar]
    about = " "
   

#DefaultContentLanguage = "en"
# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
